"""Create initial tables

Revision ID: 6d9c429baf55
Revises: 
Create Date: 2025-06-27 15:07:08.219093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d9c429baf55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linting_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键'),
    sa.Column('job_id', sa.String(length=255), nullable=False, comment='对外暴露的UUID工作ID'),
    sa.Column('status', sa.Enum('ACCEPTED', 'PROCESSING', 'COMPLETED', 'PARTIALLY_COMPLETED', 'FAILED', name='job_status_enum'), nullable=False, comment='工作总体状态'),
    sa.Column('submission_type', sa.Enum('SINGLE_FILE', 'ZIP_ARCHIVE', name='submission_type_enum'), nullable=False, comment='提交类型'),
    sa.Column('source_path', sa.String(length=1024), nullable=False, comment='在NFS共享目录中的源文件相对路径'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='工作级别的错误信息（如解压失败）'),
    sa.Column('created_at', sa.DateTime(timezone=6), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=6), nullable=False, comment='最后更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_status_created', 'linting_jobs', ['status', 'created_at'], unique=False)
    op.create_index('idx_job_type_status', 'linting_jobs', ['submission_type', 'status'], unique=False)
    op.create_index(op.f('ix_linting_jobs_job_id'), 'linting_jobs', ['job_id'], unique=True)
    op.create_table('linting_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键'),
    sa.Column('task_id', sa.String(length=255), nullable=False, comment='Celery任务的UUID'),
    sa.Column('job_id', sa.String(length=255), nullable=False, comment='关联到linting_jobs.job_id'),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILURE', name='task_status_enum'), nullable=False, comment='单个文件的处理状态'),
    sa.Column('source_file_path', sa.String(length=1024), nullable=False, comment='单个SQL文件在NFS共享目录中的相对路径'),
    sa.Column('result_file_path', sa.String(length=1024), nullable=True, comment='结果JSON文件在NFS共享目录中的相对路径'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='文件级别的错误信息'),
    sa.Column('created_at', sa.DateTime(timezone=6), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=6), nullable=False, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['job_id'], ['linting_jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_job_created', 'linting_tasks', ['job_id', 'created_at'], unique=False)
    op.create_index('idx_task_job_status', 'linting_tasks', ['job_id', 'status'], unique=False)
    op.create_index('idx_task_status_created', 'linting_tasks', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_linting_tasks_job_id'), 'linting_tasks', ['job_id'], unique=False)
    op.create_index(op.f('ix_linting_tasks_task_id'), 'linting_tasks', ['task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_linting_tasks_task_id'), table_name='linting_tasks')
    op.drop_index(op.f('ix_linting_tasks_job_id'), table_name='linting_tasks')
    op.drop_index('idx_task_status_created', table_name='linting_tasks')
    op.drop_index('idx_task_job_status', table_name='linting_tasks')
    op.drop_index('idx_task_job_created', table_name='linting_tasks')
    op.drop_table('linting_tasks')
    op.drop_index(op.f('ix_linting_jobs_job_id'), table_name='linting_jobs')
    op.drop_index('idx_job_type_status', table_name='linting_jobs')
    op.drop_index('idx_job_status_created', table_name='linting_jobs')
    op.drop_table('linting_jobs')
    # ### end Alembic commands ###
