"""Add user_id column to linting_jobs table

Revision ID: add_user_id_column
Revises: add_dialect_column
Create Date: 2025-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_user_id_column'
down_revision = 'add_dialect_column'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linting_jobs', sa.Column('user_id', sa.String(length=255), nullable=False, comment='创建工作的用户ID'))
    op.create_index('ix_linting_jobs_user_id', 'linting_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_linting_jobs_user_id', table_name='linting_jobs')
    op.drop_column('linting_jobs', 'user_id')
    # ### end Alembic commands ### 