"""Add dialect column to linting_jobs table

Revision ID: add_dialect_column
Revises: 6d9c429baf55
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_dialect_column'
down_revision = '6d9c429baf55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linting_jobs', sa.Column('dialect', sa.String(length=50), nullable=False, server_default='ansi', comment='SQLFluff方言，如mysql、postgres、bigquery等'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linting_jobs', 'dialect')
    # ### end Alembic commands ### 