"""Add boc_batch_number and boc_task_number columns to linting_jobs table

Revision ID: add_boc_fields_column
Revises: add_product_name_column
Create Date: 2025-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_boc_fields_column'
down_revision = 'add_product_name_column'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linting_jobs', sa.Column('boc_batch_number', sa.String(length=255), nullable=True, comment='BOC批次号'))
    op.add_column('linting_jobs', sa.Column('boc_task_number', sa.String(length=255), nullable=True, comment='BOC任务号'))
    op.create_index('ix_linting_jobs_boc_batch_number', 'linting_jobs', ['boc_batch_number'], unique=False)
    op.create_index('ix_linting_jobs_boc_task_number', 'linting_jobs', ['boc_task_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_linting_jobs_boc_task_number', table_name='linting_jobs')
    op.drop_index('ix_linting_jobs_boc_batch_number', table_name='linting_jobs')
    op.drop_column('linting_jobs', 'boc_task_number')
    op.drop_column('linting_jobs', 'boc_batch_number')
    # ### end Alembic commands ### 