"""Add rules column to linting_jobs table

Revision ID: add_rules_column
Revises: add_product_name_to_linting_jobs
Create Date: 2025-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = 'add_rules_column'
down_revision = 'add_boc_fields_column'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linting_jobs', sa.Column('rules', sa.JSON(), nullable=True, comment='用户指定的SQLFluff规则列表，如["RF02", "L032"]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linting_jobs', 'rules')
    # ### end Alembic commands ### 