"""Add product_name column to linting_jobs table

Revision ID: add_product_name_column
Revises: add_user_id_column
Create Date: 2025-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_product_name_column'
down_revision = 'add_user_id_column'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linting_jobs', sa.Column('product_name', sa.String(length=255), nullable=False, comment='产品名称'))
    op.create_index('ix_linting_jobs_product_name', 'linting_jobs', ['product_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_linting_jobs_product_name', table_name='linting_jobs')
    op.drop_column('linting_jobs', 'product_name')
    # ### end Alembic commands ### 